# Masters Project
## 1)Reading the dataset

In [1]:
import pandas as pd
import numpy as np
import os 

In [2]:
os.chdir('C:\\Users\\pc\\Documents\MP')
messages = pd.read_csv('Project_Dataset.txt', sep = '\t', names = ['Label', 'Message'])

In [3]:
messages = pd.read_csv('C:/Users/pc/Documents/MP/Project_Dataset.txt', sep = '\t', names = ['Label', 'Message'])

In [4]:
messages[:1]

Label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...

In [5]:
messages.head()

Label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

#### Couldn't read all the rows. Hence, the count of maximum rows that can be displayed is being calculated.

In [6]:
pd.options.display.max_rows

60

#### 60 is very low. Trying to print all the rows

In [7]:
pd.options.display.max_rows = 5572

## 2) Information about the dataset

In [8]:
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Label    5572 non-null   object
 1   Message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


#### Finding the missing values

In [9]:
messages.isnull().sum()

Label      0
Message    0
dtype: int64

##### No missing values are found.

#### Calculating the shape of dataframe

In [10]:
messages.shape

(5572, 2)

#### Finding the exact count of Target Variables

In [11]:
messages['Label'].value_counts()

ham     4825
spam     747
Name: Label, dtype: int64

## 3) Adding Length and Punctuation columns to dataset

#### Adding length

In [12]:
length = []
for i in range(len(messages)):
    length.append(len(messages['Message'][i]))

In [13]:
messages['Length'] = length
messages.head()

Label                                            Message  Length
0   ham  Go until jurong point, crazy.. Available only ...     111
1   ham                      Ok lar... Joking wif u oni...      29
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
3   ham  U dun say so early hor... U c already then say...      49
4   ham  Nah I don't think he goes to usf, he lives aro...      61


#### Adding Punctuation

In [14]:
import string
count = 0
punct = []
for i in range(len(messages)):
    for j in messages['Message'][i]:
        if j in string.punctuation:
            count+=1
    punct.append(count)
    count = 0
messages['Punctuation'] = punct
messages.head(5)

Label                                            Message  Length  \
0   ham  Go until jurong point, crazy.. Available only ...     111   
1   ham                      Ok lar... Joking wif u oni...      29   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155   
3   ham  U dun say so early hor... U c already then say...      49   
4   ham  Nah I don't think he goes to usf, he lives aro...      61   

   Punctuation  
0            9  
1            6  
2            6  
3            6  
4            2

## 4) Text Cleaning

In [15]:
messages.head(1)

Label                                            Message  Length  \
0   ham  Go until jurong point, crazy.. Available only ...     111   

   Punctuation  
0            9

In [16]:
import nltk

In [17]:
type(nltk.stem)

module

In [18]:
import re, nltk  # Regular Expression Module and Natural Language Tool Kit(2 libraries are imported)

from nltk.corpus import stopwords  # Here nltk.corpus is a Lazy Module. Lazy Module means the import of the module shouldn't 
                                   #occur until the module is actually referenced during execution.
from nltk.stem import WordNetLemmatizer # Here nltk.stem is a module.
# Here stopwords is a module and WordNetLemmatizer is a class.
lemmatizer = WordNetLemmatizer()

corpus = []
#for i in range(2):
for i in range(len(messages)):
        words = re.sub('[^a-zA-Z]', ' ', messages['Message'][i])
        #print(words)
        words = words.lower()
        words = words.split()
        
        #print(words)
        #print(type(words))
        words = [lemmatizer.lemmatize(word) for word in words if word not in stopwords.words('english')]
        #print(words)
        words = ' '.join(words)
        #print(words)
        corpus.append(words)
        #print(corpus)
        #print('--------------------------')

In [19]:
type(stopwords.words('english'))

list

#### Printing corpus(The list which contains new messages that are filtered)

In [20]:
corpus[:5]

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though']

#### Replacing the Message column in messages dataframe with new corpus list

In [21]:
messages['Message'] = corpus
messages.head()

Label                                            Message  Length  \
0   ham  go jurong point crazy available bugis n great ...     111   
1   ham                            ok lar joking wif u oni      29   
2  spam  free entry wkly comp win fa cup final tkts st ...     155   
3   ham                u dun say early hor u c already say      49   
4   ham                nah think go usf life around though      61   

   Punctuation  
0            9  
1            6  
2            6  
3            6  
4            2

#### Recalculating Length and Punctuation of new dataframe after filtering messages

In [22]:
newlength = []
for i in range(len(messages)):
    newlength.append(len(messages['Message'][i]))
messages['NewLength'] = newlength

count = 0
newpunct = []
for i in range(len(messages)):
    for j in messages['Message'][i]:
        if j in string.punctuation:
            count+=1
    newpunct.append(count)
    count = 0
messages['NewPunctuation'] = newpunct
messages.head()

Label                                            Message  Length  \
0   ham  go jurong point crazy available bugis n great ...     111   
1   ham                            ok lar joking wif u oni      29   
2  spam  free entry wkly comp win fa cup final tkts st ...     155   
3   ham                u dun say early hor u c already say      49   
4   ham                nah think go usf life around though      61   

   Punctuation  NewLength  NewPunctuation  
0            9         82               0  
1            6         23               0  
2            6        101               0  
3            6         35               0  
4            2         35               0

In [25]:
messages.sum()

Label             hamhamspamhamhamspamhamhamspamspamhamspamspamh...
Message           go jurong point crazy available bugis n great ...
Length                                                       448492
Punctuation                                                   23277
NewLength                                                    275045
NewPunctuation                                                    0
dtype: object

In [26]:
list(messages)

['Label', 'Message', 'Length', 'Punctuation', 'NewLength', 'NewPunctuation']

## 5) Analyzing the difference between spam and ham messages

In [27]:
spam_messages  = messages[messages['Label'] == 'spam']
ham_messages = messages[messages['Label'] == 'ham']
spam_messages

Label                                            Message  Length  \
2     spam  free entry wkly comp win fa cup final tkts st ...     155   
5     spam  freemsg hey darling week word back like fun st...     147   
8     spam  winner valued network customer selected receiv...     157   
9     spam  mobile month u r entitled update latest colour...     154   
11    spam  six chance win cash pound txt csh send cost p ...     136   
12    spam  urgent week free membership prize jackpot txt ...     155   
15    spam  xxxmobilemovieclub use credit click wap link n...     149   
19    spam  england v macedonia dont miss goal team news t...     155   
34    spam  thanks subscription ringtone uk mobile charged...     158   
42    spam  rodger burn msg tried call reply sm free nokia...     172   
54    spam  sm ac sptv new jersey devil detroit red wing p...     120   
56    spam  congrats year special cinema pas call c suprma...     161   
65    spam  valued customer pleased advise following recen...     152   
67    spam  urgent ur awarded complimentary trip eurodisin...     159   
68    spam             hear new divorce barbie come ken stuff      78   
93    spam  please call customer service representative pm...     137   
95    spam  free ringtone waiting collected simply text pa...     158   
114   spam  gent trying contact last weekend draw show pri...     158   
117   spam  winner u specially selected receive holiday fl...     152   
120   spam  private account statement show unredeemed bonu...     144   
121   spam  urgent mobile awarded bonus caller prize final...     156   
123   spam  today voda number ending selected receive awar...     156   
134   spam  sunshine quiz wkly q win top sony dvd player u...     125   
135   spam  want get laid tonight want real dogging locati...     162   
139   spam  rcv msg chat svc free hardcore service text go...     155   
147   spam  freemsg replied text randy sexy female live lo...     159   
159   spam  customer service annoncement new year delivery...     124   
160   spam  winner u specially selected receive cash holid...     145   
164   spam  pls stop bootydelious f inviting friend reply ...     152   
165   spam  bangbabes ur order way u receive service msg d...     155   
167   spam  urgent trying contact last weekend draw show p...     156   
188   spam  please call customer service representative fr...     147   
191   spam  unique enough find th august www areyouunique ...      72   
225   spam  new mobile must go txt nokia collect today www...     142   
227   spam  u meet ur dream partner soon ur career flyng s...     137   
235   spam  text meet someone sexy today u find date even ...     157   
240   spam  u secret admirer looking make contact u find r...     145   
250   spam  congratulation ur awarded cd voucher gift guar...     150   
259   spam  tried contact reply offer video handset anytim...     154   
264   spam  hey really horny want chat see naked text hot ...     121   
268   spam  ur ringtone service changed free credit go clu...     159   
270   spam  ringtone club get uk single chart mobile week ...     133   
273   spam  hmv bonus special pound genuine hmv voucher an...     155   
296   spam  mobile customer may claim free camera phone up...     159   
305   spam  sm ac blind date u rodds aberdeen united kingd...     146   
309   spam  themob check newest selection content game ton...     138   
312   spam  think ur smart win week weekly quiz text play ...     133   
319   spam  december mobile mths entitled update latest co...     157   
333   spam  call germany penny per minute call fixed line ...     128   
335   spam  valentine day special win quiz take partner tr...     158   
349   spam  fancy shag interested sextextuk com txt xxuk s...     111   
357   spam  congratulation ur awarded cd voucher gift guar...     150   
358   spam  ur cash balance currently pound maximize ur ca...     148   
367   spam  update xmas offer latest motorola sonyericsson...  

In [28]:
ham_messages

Label                                            Message  Length  \
0      ham  go jurong point crazy available bugis n great ...     111   
1      ham                            ok lar joking wif u oni      29   
3      ham                u dun say early hor u c already say      49   
4      ham                nah think go usf life around though      61   
6      ham      even brother like speak treat like aid patent      77   
7      ham  per request melle melle oru minnaminunginte nu...     160   
10     ham  gonna home soon want talk stuff anymore tonigh...     109   
13     ham  searching right word thank breather promise wo...     196   
14     ham                                        date sunday      35   
16     ham                                      oh k watching      26   
17     ham  eh u remember spell name yes v naughty make v wet      81   
18     ham                         fine way u feel way gota b      56   
20     ham                               seriously spell name      41   
21     ham                       going try month ha ha joking      47   
22     ham                       pay first lar da stock comin      52   
23     ham  aft finish lunch go str lor ard smth lor u fin...      88   
24     ham                 ffffffffff alright way meet sooner      57   
25     ham  forced eat slice really hungry tho suck mark g...     144   
26     ham                              lol always convincing      30   
27     ham  catch bus frying egg make tea eating mom left ...     134   
28     ham                 back amp packing car let know room      75   
29     ham           ahhh work vaguely remember feel like lol      64   
30     ham      wait still clear sure sarcastic x want live u     130   
31     ham  yeah got v apologetic n fallen actin like spoi...     189   
32     ham                                    k tell anything      29   
33     ham                fear fainting housework quick cuppa      84   
35     ham  yup ok go home look timing msg xuhui going lea...     122   
36     ham                        oops let know roommate done      47   
37     ham                                   see letter b car      28   
38     ham                              anything lor u decide      27   
39     ham  hello saturday go texting see decided anything...     155   
40     ham  pls go ahead watt wanted sure great weekend ab...      82   
41     ham  forget tell want need crave love sweet arabian...     142   
43     ham                                             seeing      19   
44     ham        great hope like man well endowed lt gt inch      72   
45     ham                           call message missed call      32   
46     ham                     get hep b immunisation nigeria      45   
47     ham                         fair enough anything going      31   
48     ham    yeah hopefully tyler could maybe ask around bit      67   
49     ham  u know stubborn even want go hospital kept tel...     148   
50     ham                       thinked first time saw class      58   
51     ham  gram usually run like lt gt half eighth smarte...     124   
52     ham  k fyi x ride early tomorrow morning crashing p...      80   
53     ham  wow never realized embarassed accomodations th...     289   
55     ham     know mallika sherawat yesterday find lt url gt      76   
57     ham                           sorry call later meeting      34   
58     ham                                       tell reached      22   
59     ham                        yes gauti sehwag odi series      40   
60     ham  gonna pick burger way home even move pain killing     108   
61     ham           ha ha ha good joke girl situation seeker      48   
62     ham                                   part checking iq      25   
63     ham                sorry roommate took forever ok come      56   
64     ham  ok lar double check wif da hair dresser alread...     110   
66     ham  today song dedicated day song u dedicate send ...  

In [29]:
messages.mean()

C:\Users\pc\AppData\Local\Temp\ipykernel_11348\3713610848.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  messages.mean()


Length            80.490309
Punctuation        4.177495
NewLength         49.361989
NewPunctuation     0.000000
dtype: float64

In [30]:
spam_messages['Punctuation'].mean()

5.712182061579652

In [31]:
ham_messages['Length'].mean()

71.48290155440415

In [32]:
ham_messages['Punctuation'].mean()

3.9398963730569947

## 6) Splitting the 2features from the dataset.

In [23]:
X = messages['Message']
X.head()

0    go jurong point crazy available bugis n great ...
1                              ok lar joking wif u oni
2    free entry wkly comp win fa cup final tkts st ...
3                  u dun say early hor u c already say
4                  nah think go usf life around though
Name: Message, dtype: object

In [24]:
type(X)

pandas.core.series.Series

In [25]:
y= messages['Label']
y.head()

0     ham
1     ham
2    spam
3     ham
4     ham
Name: Label, dtype: object

In [26]:
type(y)

pandas.core.series.Series

In [27]:
X.shape, y.shape

((5572,), (5572,))

In [28]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix

In [29]:
#tfidf = TfidfVectorizer()

pipeline_svm = Pipeline([('tfidf', TfidfVectorizer()), ('svm', LinearSVC())])

pipeline_mnb = Pipeline([('tfidf', TfidfVectorizer()), ('mnb', MultinomialNB())])

pipeline_knn = Pipeline([('tfidf', TfidfVectorizer()), ('knn', KNeighborsClassifier())])


In [31]:
pipeline_svm[0]

TfidfVectorizer()

## Case 1) test_size = 0.1

In [32]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size = 0.1, train_size = 0.9, random_state=20)
print('length of X_train1 = {} & length of X_test1 = {}'.format(len(X_train1), len(X_test1)))

length of X_train1 = 5014 & length of X_test1 = 558


### SVM Classifier

In [33]:
pipeline_svm.fit(X_train1, y_train1)
y_preds_svm1 = pipeline_svm.predict(X_test1)

### Naive Bayes Classifier

In [34]:
pipeline_mnb.fit(X_train1, y_train1)
y_preds_mnb1 = pipeline_mnb.predict(X_test1)

### KNN Classifier

In [35]:
pipeline_knn.fit(X_train1, y_train1)
y_preds_knn1 = pipeline_knn.predict(X_test1)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [36]:
y_preds1 = [y_preds_svm1, y_preds_mnb1, y_preds_knn1]
classifier = ['SVM CLASSIFIER', 'NAIVEBAYES CLASSIFIER', 'KNN CLASSIFIER']
print('CASE1 : Testsize = 10% and Trainsize = 90%')
for i in range(len(y_preds1)):
    print(classifier[i])
    print(confusion_matrix(y_test1, y_preds1[i]))
    print(classification_report(y_test1, y_preds1[i]))

CASE1 : Testsize = 10% and Trainsize = 90%
SVM CLASSIFIER
[[474   1]
 [  8  75]]
              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       475
        spam       0.99      0.90      0.94        83

    accuracy                           0.98       558
   macro avg       0.99      0.95      0.97       558
weighted avg       0.98      0.98      0.98       558

NAIVEBAYES CLASSIFIER
[[474   1]
 [ 20  63]]
              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       475
        spam       0.98      0.76      0.86        83

    accuracy                           0.96       558
   macro avg       0.97      0.88      0.92       558
weighted avg       0.96      0.96      0.96       558

KNN CLASSIFIER
[[475   0]
 [ 48  35]]
              precision    recall  f1-score   support

         ham       0.91      1.00      0.95       475
        spam       1.00      0.42      0.59        83

    accuracy      

## Case 2) test_size = 0.2

In [37]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size = 0.2, train_size = 0.8, random_state=20)
print('length of X_train2 = {} & length of X_test2 = {}'.format(len(X_train2), len(X_test2)))

length of X_train2 = 4457 & length of X_test2 = 1115


### SVM Classifier

In [38]:
pipeline_svm.fit(X_train2, y_train2)
y_preds_svm2 = pipeline_svm.predict(X_test2)

### NaiveBayes Classifier

In [39]:
pipeline_mnb.fit(X_train2, y_train2)
y_preds_mnb2 = pipeline_mnb.predict(X_test2)

### KNN Classifier

In [40]:
pipeline_knn.fit(X_train2, y_train2)
y_preds_knn2 = pipeline_knn.predict(X_test2)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [41]:
y_preds2 = [y_preds_svm2, y_preds_mnb2, y_preds_knn2]
print('CASE2 : Testsize = 20% and Trainsize = 80%')
for i in range(len(y_preds2)):
    print(classifier[i]) 
    print(confusion_matrix(y_test2, y_preds2[i]))
    print(classification_report(y_test2, y_preds2[i]))

CASE2 : Testsize = 20% and Trainsize = 80%
SVM CLASSIFIER
[[945   7]
 [ 15 148]]
              precision    recall  f1-score   support

         ham       0.98      0.99      0.99       952
        spam       0.95      0.91      0.93       163

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

NAIVEBAYES CLASSIFIER
[[951   1]
 [ 40 123]]
              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       952
        spam       0.99      0.75      0.86       163

    accuracy                           0.96      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.96      0.96      0.96      1115

KNN CLASSIFIER
[[952   0]
 [103  60]]
              precision    recall  f1-score   support

         ham       0.90      1.00      0.95       952
        spam       1.00      0.37      0.54       163

    accuracy      

## Case 3) test_size = 0.3

In [42]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y, test_size = 0.3, train_size = 0.7, random_state=20)
print('length of X_train3 = {} & length of X_test3 = {}'.format(len(X_train3), len(X_test3)))

length of X_train3 = 3900 & length of X_test3 = 1672


### SVM Classifier

In [43]:
pipeline_svm.fit(X_train3, y_train3)
y_preds_svm3 = pipeline_svm.predict(X_test3)

In [44]:
type(y_preds_svm3)

numpy.ndarray

### Naive Bayes Classifer

In [45]:
pipeline_mnb.fit(X_train3, y_train3)
y_preds_mnb3 = pipeline_mnb.predict(X_test3)

### KNN Classifier

In [46]:
pipeline_knn.fit(X_train3, y_train3)
y_preds_knn3 = pipeline_knn.predict(X_test3)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [47]:
y_preds3 = [y_preds_svm3, y_preds_mnb3, y_preds_knn3]
print('CASE3 : Testsize = 30% and Trainsize = 70%')
for i in range(len(y_preds3)):
    print(classifier[i])
    print(confusion_matrix(y_test3, y_preds3[i]))
    print(classification_report(y_test3, y_preds3[i]))

CASE3 : Testsize = 30% and Trainsize = 70%
SVM CLASSIFIER
[[1426   10]
 [  23  213]]
              precision    recall  f1-score   support

         ham       0.98      0.99      0.99      1436
        spam       0.96      0.90      0.93       236

    accuracy                           0.98      1672
   macro avg       0.97      0.95      0.96      1672
weighted avg       0.98      0.98      0.98      1672

NAIVEBAYES CLASSIFIER
[[1435    1]
 [  65  171]]
              precision    recall  f1-score   support

         ham       0.96      1.00      0.98      1436
        spam       0.99      0.72      0.84       236

    accuracy                           0.96      1672
   macro avg       0.98      0.86      0.91      1672
weighted avg       0.96      0.96      0.96      1672

KNN CLASSIFIER
[[1436    0]
 [ 156   80]]
              precision    recall  f1-score   support

         ham       0.90      1.00      0.95      1436
        spam       1.00      0.34      0.51       236

    ac

## Case 4) test_size = 0.4

In [48]:
X_train4, X_test4, y_train4, y_test4 = train_test_split(X, y, test_size = 0.4, train_size = 0.6, random_state=20)
print('length of X_train4 = {} & length of X_test4 = {}'.format(len(X_train4), len(X_test4)))

length of X_train4 = 3343 & length of X_test4 = 2229


### SVM Classifier

In [49]:
pipeline_svm.fit(X_train4, y_train4)
y_preds_svm4 = pipeline_svm.predict(X_test4)

### NaiveBayes Classifier

In [50]:
pipeline_mnb.fit(X_train4, y_train4)
y_preds_mnb4 = pipeline_mnb.predict(X_test4)

### KNN Classifier

In [51]:
pipeline_knn.fit(X_train4, y_train4)
y_preds_knn4 = pipeline_knn.predict(X_test4)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [52]:
y_preds4 = [y_preds_svm4, y_preds_mnb4, y_preds_knn4]
print('CASE4 : Testsize = 40% and Trainsize = 60%')
for i in range(len(y_preds4)):
    print(classifier[i])
    print(confusion_matrix(y_test4, y_preds4[i]))
    print(classification_report(y_test4, y_preds4[i]))

CASE4 : Testsize = 40% and Trainsize = 60%
SVM CLASSIFIER
[[1920    8]
 [  35  266]]
              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      1928
        spam       0.97      0.88      0.93       301

    accuracy                           0.98      2229
   macro avg       0.98      0.94      0.96      2229
weighted avg       0.98      0.98      0.98      2229

NAIVEBAYES CLASSIFIER
[[1927    1]
 [  85  216]]
              precision    recall  f1-score   support

         ham       0.96      1.00      0.98      1928
        spam       1.00      0.72      0.83       301

    accuracy                           0.96      2229
   macro avg       0.98      0.86      0.91      2229
weighted avg       0.96      0.96      0.96      2229

KNN CLASSIFIER
[[1928    0]
 [ 211   90]]
              precision    recall  f1-score   support

         ham       0.90      1.00      0.95      1928
        spam       1.00      0.30      0.46       301

    ac

## Case 5) test_size = 0.5

In [53]:
X_train5, X_test5, y_train5, y_test5 = train_test_split(X, y, test_size = 0.5, train_size = 0.5, random_state=20)
print('length of X_train5 = {} & length of X_test5 = {}'.format(len(X_train5), len(X_test5)))

length of X_train5 = 2786 & length of X_test5 = 2786


### SVM Classifier

In [54]:
pipeline_svm.fit(X_train5, y_train5)
y_preds_svm5 = pipeline_svm.predict(X_test5)

### Naive Bayes Classifier

In [55]:
pipeline_mnb.fit(X_train5, y_train5)
y_preds_mnb5 = pipeline_mnb.predict(X_test5)

### KNN Classifier

In [56]:
pipeline_knn.fit(X_train5, y_train5)
y_preds_knn5 = pipeline_knn.predict(X_test5)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [57]:
y_preds5 = [y_preds_svm5, y_preds_mnb5, y_preds_knn5]
print('CASE5 : Testsize = 50% and Trainsize = 50%')
for i in range(len(y_preds5)):
    print(classifier[i])
    print(confusion_matrix(y_test5, y_preds5[i]))
    print(classification_report(y_test5, y_preds5[i], output_dict = False))

CASE5 : Testsize = 50% and Trainsize = 50%
SVM CLASSIFIER
[[2414   11]
 [  42  319]]
              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      2425
        spam       0.97      0.88      0.92       361

    accuracy                           0.98      2786
   macro avg       0.97      0.94      0.96      2786
weighted avg       0.98      0.98      0.98      2786

NAIVEBAYES CLASSIFIER
[[2424    1]
 [ 100  261]]
              precision    recall  f1-score   support

         ham       0.96      1.00      0.98      2425
        spam       1.00      0.72      0.84       361

    accuracy                           0.96      2786
   macro avg       0.98      0.86      0.91      2786
weighted avg       0.97      0.96      0.96      2786

KNN CLASSIFIER
[[2425    0]
 [ 265   96]]
              precision    recall  f1-score   support

         ham       0.90      1.00      0.95      2425
        spam       1.00      0.27      0.42       361

    ac